## NumPy fundamentals

Here, I'm working through several parts of the numpy docs and make sense of it. Covered: <br>
     - [Indexing on ndarrays](https://numpy.org/doc/stable/user/basics.indexing.html) <br>

### Indexing on `ndarrays`
- the three kinds of indexing are basic indexing, advanced indexing and field access

#### Basic indexing

In [1]:
import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
x.shape = (2, 5)  # now x is 2-dimensional
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
# these are the same, x[0,-1] is however more efficient, because the extraction happens
# in the same operation

x[0][-1] == x[0,-1]

np.True_

In [ ]:
# indexing a multidimensional array with fewer indices than dimensions, we get a
# subdimensional array

x[0] #  that's a view on the array x

array([0, 1, 2, 3, 4])

In [ ]:
# slicing goes [start:stop:step]

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

x[1:7:2] # array([1, 3, 5])
x[-2:10] # array([8, 9])
x[-3:3:-1] # array([7, 6, 5, 4])
x[5:] # array([5, 6, 7, 8, 9])

array([5, 6, 7, 8, 9])

In [ ]:
# if the number of objects in the selection tuple is less than the number of the
# dimensions, then `:` (or `np.newaxis`) is assumed for any subsequent dimensions:

x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x.shape # (2, 3, 1)
x[1:2] 
# here we are giving giving just one index (a slice on axis 0), and not saying anything
# about axes 1 and 2, which are filled up with `:` (like `x[1:2, :, :]`)

array([[[4],
        [5],
        [6]]])

In [ ]:
# note on dimensions and axis:

x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x 
#  array([[[1],
#         [2],
#         [3]],
# 
#        [[4],
#         [5],
#         [6]]])

x.shape # (2, 3, 1)

# the axis are read from the outside to the inside:
# axis 0 contains 2 lists, thus x.shape[0] = 2
# axis 1 contains 3 lists, thus x.shape[1] = 3
# axis 3 contains 1 element, thus x.shape[2] = 1

# a more visual-friendly way to write this down is:
# [
#   [[1], [2], [3]],
#   [[4], [5], [6]]
# ]

# another way to think of this is that the outmost axis is the lastest to join the game:

# axis 0  (Depth / "stack"): the outermost list — 2 blocks → x[0], x[1]
# axis 1 (Rows): inside each block, 3 rows → x[0][0], x[0][1], x[0][2]
# axis 2 (Columns): each row has 1 column → x[0][0][0] is the number 1

(2, 3, 1)

In [24]:
x[..., 0] == x[:, : , 0]

array([[ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# newaxis and None can be use to add a new axis; the result is a view on x

x[:, np.newaxis, :, :].shape

(2, 1, 3, 1)

In [ ]:
x.shape # x still stays the same then ...

(2, 3, 1)

In [37]:
x = np.arange(5)

x # array([0, 1, 2, 3, 4])
x[:, np.newaxis]
# array([[0],
#        [1],
#        [2],
#        [3],
#        [4]])

x[np.newaxis, :] # array([[0, 1, 2, 3, 4]])

x[:, np.newaxis] + x[np.newaxis, :]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

#### Advanced indexing
- different indexing mechanism
- triggered when the selection object (the thing in the squared brackets) is a non-tuple
  sequence object, an ndarray (of data type integer or bool), or a tuple with at least
  one sequence object or ndarray (of data type integer or bool)
- always returns a copy

Warning from the docs: `x[(1, 2, 3),]` (advanced indexing) is fundamentally different than `x[(1, 2, 3)]` (basic indexing)! 🤯

In [43]:
# let's try this out:
x = np.arange(27).reshape(3,3,3)

# basic indexing
x[(2,2,2)]
# np.int64(26)

# advanced indexing
x[(2,2,2),]

array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

😱 :scream:

`x[(2,2,2),]` gets interpreted as repeated access to the element at index 2 at the outmost axis

In [42]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])