## NumPy fundamentals

Here, I work through some parts of the numpy docs and make sense of it by trying code and asking LLMs for more detailed reasons for why things are as they are. Covered docs: <br>
     - [Indexing on ndarrays](https://numpy.org/doc/stable/user/basics.indexing.html) <br>
     - [np.xi_](https://numpy.org/doc/stable/reference/generated/numpy.ix_.html#numpy.ix_) <br>
     - [Indexing routines](https://numpy.org/doc/stable/reference/routines.indexing.html#routines-indexing)

#### Shape, size and dimension
- dimensions (`ndim` attribute) is the number of axes (levels of indexing) in the array.
- the shape (`shape` attribute) is a tuple representing the size in each dimension
- the size (`size` attribute) is the number of elements in an array / part of the array


In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
a
# array([[1, 2, 3],
#        [4, 5, 6]])

a.ndim # 2
a.shape # (2, 3)
a.size # 6

6

### Indexing on `ndarrays`
- the three kinds of indexing are basic indexing, advanced indexing and field access

#### Basic indexing

In [52]:
x = np.arange(10)
x # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

x.shape = (2, 5)  # now x is 2-dimensional
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# these are the same:

x[0][-1] == x[0,-1]

# x[0,-1] is however more efficient, because the extraction happens in the same
# operation

np.True_

In [45]:
# indexing a multidimensional array with fewer indices than dimensions, we get a
# subdimensional array

# that's a view on the array x
x[0] # array([0, 1, 2, 3, 4])

x[0].shape


(5,)

In [ ]:
# slicing goes [start:stop:step]

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

x[1:7:2] # array([1, 3, 5])
x[-2:10] # array([8, 9])
x[-3:3:-1] # array([7, 6, 5, 4])
x[5:] # array([5, 6, 7, 8, 9])

array([5, 6, 7, 8, 9])

In [49]:
# if the number of objects in the selection tuple is less than the number of the
# dimensions, then `:` (or `np.newaxis`) is assumed for any subsequent dimensions:

x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x.shape # (2, 3, 1)
x[1:2] 
# here we are giving just one index (a slice on axis 0), and not saying anything about
# axes 1 and 2, which are filled up with `:` (like it was `x[1:2, :, :]`)

array([[[4],
        [5],
        [6]]])

In [ ]:
# equally, consider the ellipsis, that stands for several colons
x[1:2, :, :] == x[1:2, ...]

array([[[ True],
        [ True],
        [ True]]])

In [ ]:
# note on dimensions and axis:

x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x 
#  array([[[1],
#         [2],
#         [3]],
# 
#        [[4],
#         [5],
#         [6]]])

x.shape # (2, 3, 1)

# the axis are read from the outside to the inside:
# axis 0 contains 2 lists, thus `x.shape[0]` is 2
# axis 1 contains 3 lists, thus `x.shape[1]` is 3
# axis 3 contains 1 element, thus `x.shape[2]` is 1

# a more visual-friendly way to write this down is:
# [
#   [[1], [2], [3]],
#   [[4], [5], [6]]
# ]

# another way to think of this is that the outmost axis is the lastest to join the game:

# axis 0  (Depth / "stack"): the outermost list — 2 blocks → x[0], x[1]
# axis 1 (Rows): inside each block, 3 rows → x[0][0], x[0][1], x[0][2]
# axis 2 (Columns): each row has 1 column → x[0][0][0] is the number 1

(2, 3, 1)

In [ ]:
# newaxis and None can be used to add a new axis; the result is a view on x (note:
# np.newaxis is actually just an alias for None)

x[:, np.newaxis, :, :].shape

(2, 1, 3, 1)

In [ ]:
x.shape # x still stays the same then ...

(2, 3, 1)

In [ ]:
x = np.arange(5)

x # array([0, 1, 2, 3, 4])

x[:, np.newaxis] # adds new axis on the inside
# array([[0],
#        [1],
#        [2],
#        [3],
#        [4]])

x[np.newaxis, :]  # adds new axis from the outside
# array([[0, 1, 2, 3, 4]])

x[:, np.newaxis] + x[np.newaxis, :] # performs broadcasting (adding arrays of shape (5, 1) and (1, 5))

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

#### Advanced indexing
- different indexing mechanism
- triggered when the selection object (the thing in the squared brackets) is a non-tuple
  sequence object, an ndarray (of data type integer or bool), or a tuple with at least
  one sequence object or ndarray (of data type integer or bool)
- always returns a copy

Warning from the docs: `x[(1, 2, 3),]` (advanced indexing) is fundamentally different than `x[(1, 2, 3)]` (basic indexing)! 🤯

In [69]:
# let's try this out:
x = np.arange(27).reshape(3,3,3)

x
# array([[[ 0,  1,  2],
#         [ 3,  4,  5],
#         [ 6,  7,  8]],

#        [[ 9, 10, 11],
#         [12, 13, 14],
#         [15, 16, 17]],

#        [[18, 19, 20],
#         [21, 22, 23],
#         [24, 25, 26]]])

# basic indexing
x[(2,2,2)]
# np.int64(26)

# advanced indexing
x[(2,2,2),]

array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

😱 :scream:

`x[(2,2,2),]` gets interpreted as repeated access to the element at index 2 at the
outmost axis

Attempt for an explanation: <br>
- `x[(2,2,2)]` basic indexing is a tuple which gets interpreted as one element per
  axis, like it was `x[2][2][2]`
- `x[(2,2,2),]` is a tuple with one element, and that element is another tuple, which
  gets interpreted as an array-like object for advanced indexing: it gets used as a list
  of indices along axis 0 (the outmost axis), like it was `x[2], x[2], x[2]` and
  returned as a single new array (or put differently, like it was `x[np.array([2,2,2])]`)

In [71]:
# let's try that out

x[2], x[2], x[2]

#here several arrays are returned, in advanced indexing it is all returnes as a single
#array

(array([[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]),
 array([[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]),
 array([[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]))

In [72]:
# let's try that out

x[np.array([2,2,2])]

array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
# again: that is not a view, it is a copy:

x[(2,2,2),].base

Other array-like elements that cause advanced indexing are:
- Python lists: `x[[0, 2]]`
- NumPy arrays: `x[np.array([0, 2])]`
- Boolean arrays: `x[np.array([True, False, True])]`
- Tuples of arrays: `x[[0,1],[1,0]]` (selects multiple points)

In [65]:
# example of advanced indexing using integers arrays (could be numpy arrays or lists
# containing integers that get interpreted as indexes)

x = np.arange(10, 1, -1)
x # array([10,  9,  8,  7,  6,  5,  4,  3,  2])

x[np.array([3, 3, 1, 8])] # array([7, 7, 9, 2])

x[np.array([3, 3, -3, 8])] # array([7, 7, 4, 2])

# the advanced indexing element here is that all these elements get selected from *the same* axis

array([7, 7, 4, 2])

In [76]:
# 2d example
x = np.array([[1, 2], [3, 4], [5, 6]])
x 
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

x[np.array([1, -1])] 
# takes two elements (the element on position 1 and the element on position -1) from
# axis 0 (rows)

array([[3, 4],
       [5, 6]])

In [89]:
y = np.arange(35).reshape(5, 7)
y
# array([[ 0,  1,  2,  3,  4,  5,  6],
#        [ 7,  8,  9, 10, 11, 12, 13],
#        [14, 15, 16, 17, 18, 19, 20],
#        [21, 22, 23, 24, 25, 26, 27],
#        [28, 29, 30, 31, 32, 33, 34]])

y[np.array([0, 2, 4]), np.array([0, 1, 2])] 
# first index is for axis 0 (row), second for axis 1 (column)

array([ 0, 15, 30])

In [90]:
# if the index arrays don't have the same shape, they cannot be broadcast together and
# we get an error:

y[np.array([0, 2, 4]), np.array([0, 1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [ ]:
# but a scalar could also be broadcast:

y[np.array([0, 2, 4]), 1] # here 1 is broadcast to all the columns

array([ 1, 15, 29])

In [93]:
# let's try the same with an additional dimension
y = np.arange(35).reshape(5, 7)
y = y[np.newaxis, :, :]
y
# array([[[ 0,  1,  2,  3,  4,  5,  6],
#         [ 7,  8,  9, 10, 11, 12, 13],
#         [14, 15, 16, 17, 18, 19, 20],
#         [21, 22, 23, 24, 25, 26, 27],
#         [28, 29, 30, 31, 32, 33, 34]]])

y[:, np.array([0, 2, 4]), np.array([0, 1, 2])] 
# first index is for axis 0 (batch), where we just select all, second index is for axis
# 1 (row), third for axis 2 (column)

array([[ 0, 15, 30]])

In [ ]:
# we can also only partially index an array with advanced indexing

y[:, np.array([0, 2, 4])] 
# only indexes rows (using all the batches), but leaves out the columns (meaning we use all of them)

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [14, 15, 16, 17, 18, 19, 20],
        [28, 29, 30, 31, 32, 33, 34]]])

In [ ]:
# fancy indexing
# (selecting specific elements)

x = np.array([[1, 2], [3, 4], [5, 6]])
x[[0, 1, 2], [0, 1, 0]] 
# [0, 1, 2] means row 0, row 1, row 2 
# [0, 1, 0] means column 0, column 1, column 0

array([1, 4, 5])

In [100]:
# np.xi_ also allows broadcasting, but it cannot do anything fancy indexing couldn't do:

row_indices = np.array([0, 2], dtype=np.intp)
column_indices = np.array([0, 1], dtype=np.intp)
x[np.ix_(row_indices, column_indices)]

array([[1, 2],
       [5, 6]])

We talk about boolean indexing, when the object used for indexing has a boolean dtype.
- an array object with boolean dtype could be obtained from comparison operators 

In [ ]:
# example: filtering an array

x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x[~np.isnan(x)]

array([1., 2., 3.])

In [102]:
# example: add constant to all negative elements

x = np.array([1., -1., -2., 3])
x[x < 0] += 20
x

array([ 1., 19., 18.,  3.])

In [ ]:
# if the array and the indexing array object don't match shapes

x = np.array([1., -1., -2., 3])
x[np.array([True, False, False])]

# we get an IndexError

IndexError: boolean index did not match indexed array along axis 0; size of axis is 4 but size of corresponding boolean axis is 3

In [112]:
# but the indexing array can be applied along an axis (or a subset of axis) as well:

x1 = x.reshape(2, -1)
x1
# array([[ 1., -1.],
#        [-2.,  3.]])

x1[np.array([True, False])]

# if the Boolean array’s shape matches a leading dimension, NumPy will interpret it
# along that axis.

array([[ 1., -1.]])

In [ ]:
# combining integer and boolean indexing

x1[0, np.array([True, False])]

array([1.])

This is an example from the docs ([Indexing on ndarrays](https://numpy.org/doc/stable/user/basics.indexing.html)):

In [119]:
#  combining integer and boolean indexing in a more complex example

x = np.arange(35).reshape(5, 7)
x
# array([[ 0,  1,  2,  3,  4,  5,  6],
#        [ 7,  8,  9, 10, 11, 12, 13],
#        [14, 15, 16, 17, 18, 19, 20],
#        [21, 22, 23, 24, 25, 26, 27],
#        [28, 29, 30, 31, 32, 33, 34]])

b = x > 20
b[:, 5] # only column 5
# array([False, False, False,  True,  True])

x[b[:, 5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

Here, the information if the values in the 5th column are larger than 20 is then used as
an indexing criterium for the rows.

I was wondering what the purpose of this is. It seems that pattern is a conditional row
filter. ChatGPT explained to me that this pattern is very common in data analytics and
gave me the following example:

Imagine `x` was a dataset where:
- Each row is a person
- Each column is a feature (e.g., age, weight, blood pressure...)

We could do:

x[:, 3] > 100  # people with blood pressure over 100
x[x[:, 3] > 100]  # select only those rows (people)

That pattern is like saying: “Give me all rows where the value in column col is above
threshold.” 

Now, that makes total sense to me. :)

In [123]:
# example: from an array, select all rows which sum up to less or equal two:

x = np.array([[0, 1], [1, 1], [2, 2]])
x
# array([[0, 1],
#        [1, 1],
#        [2, 2]])

rowsum = x.sum(-1)
rowsum
# array([1, 2, 4])

x[rowsum <= 2, :]

array([[0, 1],
       [1, 1]])

In [127]:
# exercise: Use a 2-D boolean array of shape (2, 3) with four True elements to select
# rows from a 3-D array of shape (2, 3, 5) results in a 2-D result of shape (4, 5):

x = np.arange(30).reshape(2, 3, 5)
x
# array([[[ 0,  1,  2,  3,  4],
#         [ 5,  6,  7,  8,  9],
#         [10, 11, 12, 13, 14]],
#
#        [[15, 16, 17, 18, 19],
#         [20, 21, 22, 23, 24],
#         [25, 26, 27, 28, 29]]])

# the task is to select rows here, there are 6 rows to pick from and we select 4:
boolean_array = np.array([True, True, False, True, False, True]).reshape(2, 3)
boolean_array
# array([[ True,  True, False],
#        [ True, False,  True]])

x[boolean_array]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

#### Combining advanced and basic indexing

In [128]:
# combining advanced indexing with a slice (from basis indexing):

y = np.arange(35).reshape(5,7)
y[np.array([0, 2, 4]), 1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [ ]:
# slicing everything possible is preferable, since we don't then create an extra copy:

x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])

x[1:2, 1:3]
# array([[4, 5]])

x[1:2, [1, 2]]
# array([[4, 5]])

# The results are the same, but the slicing is more efficient.

x[1:2, 1:3].base
# array([[ 0,  1,  2],
#        [ 3,  4,  5],
#        [ 6,  7,  8],
#        [ 9, 10, 11]])

x[1:2, [1, 2]].base
# array([[4],
#        [5]])

array([[4],
       [5]])

The base of the last line (`x[1:2, [1, 2]].base`) had been surprising to me, since I had
expected it was `None`. I found out that while advanced indexing usually returns a copy,
that copy - after mixed indexing operations - may itself be a view of some internal
temporary buffer — not the original `x`!!! 😵

Combining several kinds of indexing also allows to replace one axis with a broadcasted index array -  but honestly: who wants that? That would be a very bad design choice!

#### Field access

- is a way to access [structured arrays](https://numpy.org/doc/stable/user/basics.rec.html#structured-arrays)
- for instance:

In [133]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [ ]:
# indexing on the field names returns views on them:
x['name']

array(['Rex', 'Fido'], dtype='<U10')

#### Flat iterator indexing

[x.flat](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flat.html#numpy.ndarray.flat) returns an iterator that will iterate over the entire array:

In [ ]:
x = np.arange(6).reshape(2, 3)
x
# array([[0, 1, 2],
#        [3, 4, 5]])

x.flat[3]
# np.int64(3)

x.T.flat[3]
# np.int64(4)

# It is a 1-dimensional view.

np.int64(4)

#### Assigning values to indexed arrays

We can select a subset of an array to assign to using a single index, slices, and index and mask arrays. The value being assigned to the indexed array must be shape consistent (the same shape or broadcastable to the shape the index produces). 

- assignments are always made to the original data (not to a view)

In [141]:
# assigning a constant

x = np.arange(10)
x[2:7] = 1
x

array([0, 1, 1, 1, 1, 1, 1, 7, 8, 9])

In [142]:
# assigning an array with the right size

x = np.arange(10)
x[2:7] = np.arange(5)
x

array([0, 1, 0, 1, 2, 3, 4, 7, 8, 9])

In [ ]:
# surprising example

x = np.arange(0, 50, 10)
x
# array([ 0, 10, 20, 30, 40])

x[np.array([1, 1, 3, 1])] += 1
x # the +1 is assigned to the first index just once

array([ 0, 11, 20, 31, 40])

#### My personal highlight
while looking through numpy's docs was the docstring of [np.choose](https://numpy.org/doc/stable/reference/generated/numpy.choose.html#numpy.choose):

<font color="red">

numpy.choose(a, choices, out=None, mode='raise')

Construct an array from an index array and a list of arrays to choose from.

First of all, if confused or uncertain, definitely look at the Examples - in its full generality, this function is less simple than it might seem from the following code description:

`np.choose(a,c) == np.array([c[a[I]][I] for I in np.ndindex(a.shape)])`

... <br>
... <br>
</font>

Just saying ...
