In [3]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers


2022-11-15 12:18:04.549524: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-15 12:18:04.859032: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-11-15 12:18:04.934970: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-11-15 12:18:04.935000: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if yo

In [4]:
# --- SEQUENCE A (Paris)

day_1 = [10, 25, 50]  # OBSERVATION 1 [Temp, speed, pollution]
day_2 = [13, 10, 70]  # OBSERVATION 2 [Temp, speed, pollution]
day_3 = [ 9,  5, 90]
day_4 = [ 7,  0, 95]

sequence_a = [day_1, day_2, day_3, day_4]

y_a = 110 # Pollution day 5

# --- SEQUENCE B (Berlin)
sequence_b = [[25, 20, 30], [26, 24, 50], [28, 20, 80], [22, 3, 110]]
y_b = 125

# --- SEQUENCE C (London)
sequence_c = [[15, 10, 60], [25, 20, 65], [35, 10, 75], [36, 15, 70]]
y_c = 30

X = np.array([sequence_a, sequence_b, sequence_c]).astype(np.float32)
y = np.array([y_a, y_b, y_c]).astype(np.float32)

print(X.shape)
print(y.shape)

(3, 4, 3)
(3,)


In [6]:
model = Sequential()
model.add(layers.SimpleRNN(units=2, activation='tanh', input_shape=(4,3)))
model.add(layers.Dense(1, activation="linear"))

# The compilation
model.compile(loss='mse', 
              optimizer='rmsprop')  # Recommended optimizer for RNNs
# The fit
model.fit(X, y,
         batch_size=16,
         epochs=10, verbose=0)

# The prediction (one per sequence/city)
model.predict(X)

1/1 [==============================] - 0s 90ms/step


array([[-0.26448637],
       [-0.26448637],
       [-0.26448637]], dtype=float32)

In [7]:
print("Input shape: ", X.shape)

model.summary()

Input shape:  (3, 4, 3)
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 2)                 12        
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [14]:
# Here are the 12 weights of our RNN layer
[w.numpy().shape for w in model.layers[0].weights]

[(3, 2), (2, 2), (2,)]

In [17]:
[w for w in model.layers[0].weights]

<tf.Variable 'simple_rnn_1/simple_rnn_cell_1/kernel:0' shape=(3, 2) dtype=float32, numpy=
array([[ 0.5880741 ,  0.42127264],
       [ 0.41249084,  1.0735757 ],
       [-0.5200067 ,  0.48335147]], dtype=float32)>
<tf.Variable 'simple_rnn_1/simple_rnn_cell_1/recurrent_kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.9759035 ,  0.21820252],
       [-0.21820252,  0.9759035 ]], dtype=float32)>
<tf.Variable 'simple_rnn_1/simple_rnn_cell_1/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>


[None, None, None]